//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitScheduleEditor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransitScheduleEntities : DbContext
    {
        public TransitScheduleEntities()
            : base("name=TransitScheduleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StopDisplay> StopDisplay { get; set; }
        public virtual DbSet<tblHoliDate> tblHoliDate { get; set; }
        public virtual DbSet<StaticTrain> StaticTrains { get; set; }
    }
}
