//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitScheduleEditor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticTrain
    {
        public int StaticTrainId { get; set; }
        public string Train { get; set; }
        public string Number { get; set; }
        public string Direction { get; set; }
        public string DepartTime { get; set; }
        public string Platform { get; set; }
        public string Days { get; set; }
        public string TrainID { get; set; }
        public string BlockID { get; set; }
        public string StopID { get; set; }
        public int stop_sequence { get; set; }
        public string Trip_id { get; set; }
    }
}
