//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitScheduleEditor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopDisplay
    {
        public int StopNumber { get; set; }
        public bool Show { get; set; }
        public Nullable<int> Platform { get; set; }
        public string Description { get; set; }
        public string StopID { get; set; }
    }
}
