<%@ Page Title="Schedule Editor" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="TransitScheduleEditor._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div class="jumbotron">
        <h1>NCTD Schedule</h1>
        <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />

        <asp:Label runat="server" Text="Train:" />
        <asp:DropDownList runat="server" AutoPostBack="true" ID="DisplayTrain">
            <asp:ListItem Text="All" Value="" />
            <asp:ListItem Text="Amtrak" />
            <asp:ListItem Text="Coaster" />
            <asp:ListItem Text="Metrolink" />
            <asp:ListItem Text="Sprinter" />
        </asp:DropDownList>
        <asp:Label runat="server" Text="Run Days:" />
        <asp:DropDownList runat="server" AutoPostBack="true" ID="DisplayDays">
            <asp:ListItem Text="All" Value="" />
            <asp:ListItem Text="Weekdays" />
            <asp:ListItem Text="Weekends" />
            <asp:ListItem Text="Friday" />
            <asp:ListItem Text="Saturday" />
        </asp:DropDownList>
        <asp:Label runat="server" Text="Platform:" />
        <asp:DropDownList runat="server" AutoPostBack="true" ID="DisplayPlatform">
            <asp:ListItem Text="All" Value="" />
            <asp:ListItem Text="Platform 1" />
            <asp:ListItem Text="Platform 2" />
            <asp:ListItem Text="Platform 3" />
        </asp:DropDownList>
        
        <asp:Button ID="btnAddTrain" runat="server" Text="Add Train" PostBackUrl="~/Addtrain" />

        <asp:GridView ID="ScheduleGrid" runat="server" SelectMethod="GetTrains"
            UpdateMethod="UpdateTrain" DeleteMethod="DeleteTrain"
            AutoGenerateEditButton="False" AutoGenerateDeleteButton="False" DataKeyNames="StaticTrainId"
            ItemType="TransitScheduleEditor.Models.StaticTrain" AutoGenerateColumns="False"
            AllowSorting="True" AllowPaging="False" PageSize="20"
            OnCallingDataMethods="ScheduleGrid_CallingDataMethods" ShowFooter="False" Width="100%" >

            <RowStyle BackColor="#008c99" ForeColor="White" HorizontalAlign="Center" />
            <AlternatingRowStyle BackColor="#005daa" ForeColor="White" />
            <EditRowStyle Font-Size="Small" />
            <HeaderStyle BackColor="Black" ForeColor="White" />
            
            <Columns>
                <asp:CommandField ShowEditButton="true" ShowCancelButton="true" ShowDeleteButton="true" ButtonType="Button" 
                    UpdateText="Save" ItemStyle-Wrap="false" HeaderText="Command" HeaderStyle-ForeColor="Gray" ItemStyle-HorizontalAlign="Center" 
                    ControlStyle-ForeColor="Black" ControlStyle-Font-Size="X-Small" />
                <asp:DynamicField DataField="Departure" SortExpression="DepartTime" ItemStyle-HorizontalAlign="Center" />
                <asp:DynamicField DataField="TrainName" HeaderText="Train" SortExpression="Train" ItemStyle-HorizontalAlign="Center" />
                <asp:DynamicField DataField="Number" ItemStyle-HorizontalAlign="Center" />
                <asp:DynamicField DataField="DirectionName" HeaderText="Direction" SortExpression="Direction" ItemStyle-HorizontalAlign="Center" />
                <asp:DynamicField DataField="PlatformName" HeaderText="Platform" SortExpression="Platform" ItemStyle-HorizontalAlign="Center" />
                <asp:DynamicField DataField="DayName" HeaderText="Run Days" SortExpression="Days" ItemStyle-HorizontalAlign="Center" />
            </Columns>
        </asp:GridView>
        <asp:ObjectDataSource ID="ScheduleList"
            SelectMethod="getTrains"
            TypeName="TransitScheduleEditor.ViewModels.ScheduleEditVM"
            runat="server"></asp:ObjectDataSource>

    </div>

    </asp:Content>
