<%@ Page Title="Schedule Editor" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="TransitScheduleEditor._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div class="jumbotron">
        <h1>NCTD Schedule</h1>
        <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />

        <asp:Label runat="server" Text="Train:" />
        <asp:DropDownList runat="server" AutoPostBack="true" ID="DisplayTrain">
            <asp:ListItem Text="All" Value="" />
            <asp:ListItem Text="Amtrak" />
            <asp:ListItem Text="Coaster" />
            <asp:ListItem Text="Metrolink" />
            <asp:ListItem Text="Sprinter" />
        </asp:DropDownList>
        <asp:Label runat="server" Text="Run Days:" />
        <asp:DropDownList runat="server" AutoPostBack="true" ID="DisplayDays">
            <asp:ListItem Text="All" Value="" />
            <asp:ListItem Text="Weekdays" />
            <asp:ListItem Text="Weekends" />
            <asp:ListItem Text="Friday" />
            <asp:ListItem Text="Saturday" />
        </asp:DropDownList>
        <asp:Label runat="server" Text="Platform:" />
        <asp:DropDownList runat="server" AutoPostBack="true" ID="DisplayPlatform">
            <asp:ListItem Text="All" Value="" />
            <asp:ListItem Text="Platform 1" />
            <asp:ListItem Text="Platform 2" />
            <asp:ListItem Text="Platform 3" />
        </asp:DropDownList>
        
        <asp:HyperLink NavigateUrl="~/AddTrain" Text="Add New Train" runat="server" />
        <asp:GridView ID="ScheduleGrid" runat="server" SelectMethod="GetTrains"
            UpdateMethod="UpdateTrain" DeleteMethod="DeleteTrain"
            AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" DataKeyNames="StaticTrainId"
            ItemType="TransitScheduleEditor.Models.StaticTrain" AutoGenerateColumns="False"
            AllowSorting="True" AllowPaging="True" PageSize="20"
            OnCallingDataMethods="ScheduleGrid_CallingDataMethods" ShowFooter="True">
            <Columns>
                <asp:TemplateField ConvertEmptyStringToNull="False" HeaderText="StaticTrainId" InsertVisible="False" SortExpression="StaticTrainId">
                    <EditItemTemplate>
                        <asp:DynamicControl ID="DynamicControl1" runat="server" DataField="StaticTrainId" Mode="Edit" />
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:DynamicControl ID="DynamicControl1" runat="server" DataField="StaticTrainId" Mode="ReadOnly" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:DynamicField DataField="Departure" />
                <asp:DynamicField DataField="DepartTime" HeaderText="Depart Time" ReadOnly="true" InsertVisible="false" />
                <asp:DynamicField DataField="Train" />
                <asp:DynamicField DataField="Number" />
                <asp:DynamicField DataField="Direction" />
                <asp:DynamicField DataField="Platform" />
                <asp:DynamicField DataField="Days" HeaderText="Run Days" />
                <asp:DynamicField DataField="TrainID" HeaderText="Train ID" ReadOnly="true" InsertVisible="false" />
                <asp:DynamicField DataField="StopID" HeaderText="Stop ID" ReadOnly="true" InsertVisible="false" />
            </Columns>
        </asp:GridView>
        <asp:ObjectDataSource ID="ScheduleList"
            SelectMethod="getSchedule"
            TypeName="TransitScheduleEditor.ViewModels.ScheduleEditVM"
            runat="server"></asp:ObjectDataSource>

    </div>

    </asp:Content>
